version: '2'

services:
    web:
        image: nginx:latest
        container_name: nginx_pd
        ports:
            - 80:8080
        volumes:
            - ./code:/code
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    db:
        image: mysql:latest
        container_name: database_pd
        environment:
            - MYSQL_HOST=DB_HOST_ENDPOINT
            - MYSQL_USER=notes_api
            - MYSQL_PASSWORD=notes_api
        ports:
            - 3306:3306
        volumes:
            - ./code/database_schema.sql:/docker-entrypoint-initdb.d
        networks:
            - code-network
    node:
        build: ./node
        container_name: node_pd
        environment:
            - NODEJS_API_PORT=8888
        depends_on: 
            - db
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
